"""
WhatsApp Delivery Service — Report Delivery with Multi-Device Isolation

FIX 2: ALL operations scoped to specific user_id.
FIX 5: WhatsApp is OPTIONAL — only deliver to users who opted in.
FIX 11: Delivery confirmation tracking.

Architecture:
- Reports generated by backend, delivered via OpenWA
- Each delivery is scoped to a single user_id
- Delivery status tracked and confirmed
- Failed deliveries retried with exponential backoff
"""

import asyncio
import base64
import logging
import os
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

import httpx

logger = logging.getLogger(__name__)


@dataclass
class DeliveryResult:
    """Result of a report delivery attempt."""
    user_id: str
    success: bool
    message_id: Optional[str] = None
    error: Optional[str] = None
    attempts: int = 1
    delivered_at: Optional[datetime] = None
    delivery_confirmed: bool = False


@dataclass
class DeliveryStats:
    """Aggregate delivery statistics."""
    total: int = 0
    successful: int = 0
    failed: int = 0
    pending_confirmation: int = 0
    results: list = field(default_factory=list)


class WhatsAppDelivery:
    """
    Report delivery via WhatsApp.

    FIX 2: Every operation includes user_id for isolation.
    FIX 5: Only delivers to users who have connected WhatsApp.
    FIX 11: Tracks delivery confirmation.

    Usage:
        delivery = WhatsAppDelivery()
        stats = await delivery.send_daily_reports_to_all(db)
    """

    def __init__(self):
        self.openwa_url = os.environ.get("OPENWA_URL", "http://openwa:3000")
        self.max_retries = 3
        self.retry_base_delay = 2.0  # seconds

    async def send_report(
        self,
        user_id: str,
        phone: str,
        report_text: str,
        chart_base64: Optional[str] = None,
        voice_base64: Optional[str] = None,
    ) -> DeliveryResult:
        """
        Send a report to a specific worker via WhatsApp.

        FIX 2: user_id is explicitly required — no implicit context.
        FIX 11: Returns delivery confirmation status.

        Args:
            user_id: Target worker's user ID (REQUIRED for isolation)
            phone: Decrypted phone number
            report_text: Report content in Swahili
            chart_base64: Optional chart image (base64 PNG)
            voice_base64: Optional voice report (base64 OGG)

        Returns: DeliveryResult with success status and tracking info
        """
        if not user_id:
            raise ValueError("user_id is required for delivery isolation")

        if not phone:
            return DeliveryResult(
                user_id=user_id,
                success=False,
                error="No phone number available",
            )

        last_error = None

        for attempt in range(1, self.max_retries + 1):
            try:
                # Send text report first
                text_result = await self._send_text(user_id, phone, report_text)

                if not text_result.get("success"):
                    raise Exception(text_result.get("error", "Text send failed"))

                message_id = text_result.get("message_id")

                # Send chart image if provided
                if chart_base64:
                    try:
                        await self._send_image(user_id, phone, chart_base64, "Chati ya ripoti")
                    except Exception as e:
                        logger.warning(f"Chart delivery failed for {user_id}: {e}")
                        # Don't fail the whole delivery for chart failure

                # Send voice report if provided
                if voice_base64:
                    try:
                        await self._send_voice(user_id, phone, voice_base64)
                    except Exception as e:
                        logger.warning(f"Voice delivery failed for {user_id}: {e}")

                return DeliveryResult(
                    user_id=user_id,
                    success=True,
                    message_id=message_id,
                    attempts=attempt,
                    delivered_at=datetime.now(timezone.utc),
                    delivery_confirmed=False,  # Confirmed async via receipt
                )

            except Exception as e:
                last_error = str(e)
                logger.warning(
                    f"Delivery attempt {attempt}/{self.max_retries} failed for user {user_id}: {e}"
                )

                if attempt < self.max_retries:
                    # Exponential backoff
                    delay = self.retry_base_delay * (2 ** (attempt - 1))
                    await asyncio.sleep(delay)

        return DeliveryResult(
            user_id=user_id,
            success=False,
            error=last_error,
            attempts=self.max_retries,
        )

    async def send_daily_reports_to_all(self, db) -> DeliveryStats:
        """
        Send daily reports to all workers with WhatsApp connected.

        FIX 2: Each report delivery is scoped to individual user_id.
        FIX 5: Only sends to users who opted into WhatsApp.
        """
        from app.models.user import User

        # FIX 2: Query explicitly filters for WhatsApp-connected users
        users = db.query(User).filter(
            User.whatsapp_connected == True,  # noqa: E712
            User.is_active == True,  # noqa: E712
        ).all()

        logger.info(f"Sending daily reports to {len(users)} WhatsApp users")

        stats = DeliveryStats(total=len(users))

        for user in users:
            try:
                # FIX 2: Each delivery scoped to specific user
                phone = user.get_phone()
                report_text = self._generate_daily_report_text(user)

                result = await self.send_report(
                    user_id=str(user.id),
                    phone=phone,
                    report_text=report_text,
                )

                if result.success:
                    stats.successful += 1
                else:
                    stats.failed += 1

                stats.results.append(result)

            except Exception as e:
                logger.error(f"Failed to send report to user {user.id}: {e}")
                stats.failed += 1
                stats.results.append(DeliveryResult(
                    user_id=str(user.id),
                    success=False,
                    error=str(e),
                ))

        logger.info(
            f"Daily report delivery complete: {stats.successful} sent, "
            f"{stats.failed} failed out of {stats.total}"
        )

        return stats

    async def send_weekly_reports_to_all(self, db) -> DeliveryStats:
        """Send weekly reports to all WhatsApp-connected workers."""
        from app.models.user import User

        users = db.query(User).filter(
            User.whatsapp_connected == True,  # noqa: E712
            User.is_active == True,  # noqa: E712
        ).all()

        stats = DeliveryStats(total=len(users))

        for user in users:
            try:
                phone = user.get_phone()
                report_text = self._generate_weekly_report_text(user)

                result = await self.send_report(
                    user_id=str(user.id),
                    phone=phone,
                    report_text=report_text,
                )

                if result.success:
                    stats.successful += 1
                else:
                    stats.failed += 1
                stats.results.append(result)

            except Exception as e:
                stats.failed += 1
                stats.results.append(DeliveryResult(
                    user_id=str(user.id), success=False, error=str(e),
                ))

        return stats

    async def send_monthly_reports_to_all(self, db) -> DeliveryStats:
        """Send monthly reports to all WhatsApp-connected workers."""
        from app.models.user import User

        users = db.query(User).filter(
            User.whatsapp_connected == True,  # noqa: E712
            User.is_active == True,  # noqa: E712
        ).all()

        stats = DeliveryStats(total=len(users))

        for user in users:
            try:
                phone = user.get_phone()
                report_text = self._generate_monthly_report_text(user)

                # Monthly reports include chart
                chart_base64 = await self._generate_monthly_chart(user)

                result = await self.send_report(
                    user_id=str(user.id),
                    phone=phone,
                    report_text=report_text,
                    chart_base64=chart_base64,
                )

                if result.success:
                    stats.successful += 1
                else:
                    stats.failed += 1
                stats.results.append(result)

            except Exception as e:
                stats.failed += 1
                stats.results.append(DeliveryResult(
                    user_id=str(user.id), success=False, error=str(e),
                ))

        return stats

    # ── OpenWA Communication ────────────────────────────────────

    async def _send_text(self, user_id: str, phone: str, message: str) -> dict:
        """Send text message via OpenWA."""
        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.post(
                f"{self.openwa_url}/send-message",
                json={
                    "user_id": user_id,
                    "phone": phone,
                    "message": message,
                },
            )
            response.raise_for_status()
            return response.json()

    async def _send_image(
        self, user_id: str, phone: str, image_base64: str, caption: str = ""
    ) -> dict:
        """Send image via OpenWA."""
        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.post(
                f"{self.openwa_url}/send-image",
                json={
                    "user_id": user_id,
                    "phone": phone,
                    "image_url": f"data:image/png;base64,{image_base64}",
                    "caption": caption,
                },
            )
            response.raise_for_status()
            return response.json()

    async def _send_voice(self, user_id: str, phone: str, audio_base64: str) -> dict:
        """Send voice note via OpenWA."""
        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.post(
                f"{self.openwa_url}/send-voice",
                json={
                    "user_id": user_id,
                    "phone": phone,
                    "audio_url": f"data:audio/ogg;base64,{audio_base64}",
                },
            )
            response.raise_for_status()
            return response.json()

    # ── Report Generation ───────────────────────────────────────

    def _generate_daily_report_text(self, user) -> str:
        """Generate daily report text for a worker."""
        # TODO: Query actual transaction data
        return (
            f"📊 *Ripoti ya Leo — Msaidizi*\n\n"
            f"Habari! Hii ni ripoti yako ya leo.\n\n"
            f"💰 Mauzo: KES 0\n"
            f"📦 Manunuzi: 0\n"
            f"📈 Faida: KES 0\n\n"
            f"Tumia programu ya Msaidizi kwa maelezo zaidi.\n\n"
            f"_Ripoti hii imetumwa na Msaidizi Intelligence_"
        )

    def _generate_weekly_report_text(self, user) -> str:
        """Generate weekly report text."""
        return (
            f"📊 *Ripoti ya Wiki — Msaidizi*\n\n"
            f"Muhtasari wa wiki hii:\n\n"
            f"💰 Jumla ya Mauzo: KES 0\n"
            f"📦 Jumla ya Manunuzi: 0\n"
            f"📈 Faida ya Wiki: KES 0\n"
            f"👥 Wateja Wapya: 0\n\n"
            f"Tumia programu ya Msaidizi kwa maelezo zaidi.\n\n"
            f"_Ripoti hii imetumwa na Msaidizi Intelligence_"
        )

    def _generate_monthly_report_text(self, user) -> str:
        """Generate monthly report text."""
        return (
            f"📊 *Ripoti ya Mwezi — Msaidizi*\n\n"
            f"Muhtasari wa mwezi huu:\n\n"
            f"💰 Jumla ya Mauzo: KES 0\n"
            f"📦 Jumla ya Manunuzi: 0\n"
            f"📈 Faida ya Mwezi: KES 0\n"
            f"👥 Wateja Wapya: 0\n"
            f"📊 Ukuaji: 0%\n\n"
            f"Angalia chati iliyotumwa kwa maelezo zaidi.\n\n"
            f"_Ripoti hii imetumwa na Msaidizi Intelligence_"
        )

    async def _generate_monthly_chart(self, user) -> Optional[str]:
        """Generate monthly report chart as base64 PNG."""
        try:
            import matplotlib
            matplotlib.use("Agg")
            import matplotlib.pyplot as plt
            import io

            # TODO: Use actual transaction data
            days = list(range(1, 31))
            sales = [0] * 30  # Placeholder

            fig, ax = plt.subplots(figsize=(8, 4))
            ax.bar(days, sales, color="#2563eb")
            ax.set_xlabel("Siku")
            ax.set_ylabel("Mauzo (KES)")
            ax.set_title("Mauzo ya Mwezi")

            buf = io.BytesIO()
            fig.savefig(buf, format="png", dpi=100, bbox_inches="tight")
            plt.close(fig)

            buf.seek(0)
            return base64.b64encode(buf.read()).decode("ascii")

        except Exception as e:
            logger.warning(f"Chart generation failed: {e}")
            return None


# ── Singleton ────────────────────────────────────────────────────

_delivery: Optional[WhatsAppDelivery] = None


def get_whatsapp_delivery() -> WhatsAppDelivery:
    """Get or create the singleton WhatsAppDelivery."""
    global _delivery
    if _delivery is None:
        _delivery = WhatsAppDelivery()
    return _delivery
