"""
WhatsApp Bot Service — Command Processing

FIX 7 REDESIGN:
- WhatsApp is a SECONDARY report delivery channel
- Bot processes incoming messages (report requests, commands)
- All operations are scoped to the authenticated user
- Rate limiting per user
- HMAC signature verification on all incoming webhooks

Commands:
- "Ripoti ya leo" → Daily report
- "Ripoti ya wiki" → Weekly report
- "Ripoti ya mwezi" → Monthly report
- "Salio" → Current balance
- "Msaada" → Help text
"""

import hashlib
import hmac
import logging
import os
import time
from typing import Optional

import httpx

logger = logging.getLogger(__name__)

# Command patterns (Swahili)
COMMANDS = {
    "ripoti ya leo": "daily_report",
    "ripoti ya siku": "daily_report",
    "daily report": "daily_report",
    "ripoti ya wiki": "weekly_report",
    "weekly report": "weekly_report",
    "ripoti ya mwezi": "monthly_report",
    "monthly report": "monthly_report",
    "salio": "balance",
    "balance": "balance",
    "msaada": "help",
    "help": "help",
    "hali": "status",
    "status": "status",
}


class WhatsAppBot:
    """
    WhatsApp message handler.

    Processes incoming messages and routes to appropriate handlers.
    All operations are scoped to the authenticated user.
    """

    def __init__(self):
        self.openwa_url = os.environ.get("OPENWA_URL", "http://openwa:3000")
        self.webhook_secret = os.environ.get("BACKEND_WEBHOOK_SECRET", "")
        self._last_command_time: dict[str, float] = {}  # Rate limiting

    def verify_signature(self, payload: str, signature: str) -> bool:
        """Verify HMAC signature from OpenWA webhook."""
        if not self.webhook_secret:
            logger.error("BACKEND_WEBHOOK_SECRET not configured!")
            return False

        expected = hmac.new(
            self.webhook_secret.encode(),
            payload.encode(),
            hashlib.sha256,
        ).hexdigest()

        return hmac.compare_digest(expected, signature)

    def parse_command(self, text: str) -> Optional[str]:
        """
        Parse incoming message text to extract command.

        Returns command name or None if not a command.
        """
        if not text:
            return None

        normalized = text.strip().lower()

        for pattern, command in COMMANDS.items():
            if pattern in normalized:
                return command

        return None

    async def process_message(
        self,
        from_jid: str,
        text: str,
        user_id: str,
        message_id: Optional[str] = None,
    ) -> Optional[str]:
        """
        Process an incoming WhatsApp message.

        Args:
            from_jid: WhatsApp JID of the sender
            text: Message text
            user_id: Authenticated user ID (from backend)
            message_id: Message ID for tracking

        Returns: Response text to send back, or None if no response needed.
        """
        # Rate limiting: max 1 command per 5 seconds per user
        now = time.time()
        last_time = self._last_command_time.get(user_id, 0)
        if now - last_time < 5:
            logger.info(f"Rate limited user {user_id}")
            return "Pole, subiri kidogo kabla ya kuomba tena. ⏳"

        self._last_command_time[user_id] = now

        command = self.parse_command(text)

        if command is None:
            return self._unknown_command_response(text)

        logger.info(f"Command: {command} from user {user_id}")

        if command == "daily_report":
            return await self._generate_report(user_id, "daily")
        elif command == "weekly_report":
            return await self._generate_report(user_id, "weekly")
        elif command == "monthly_report":
            return await self._generate_report(user_id, "monthly")
        elif command == "balance":
            return await self._get_balance(user_id)
        elif command == "status":
            return await self._get_status(user_id)
        elif command == "help":
            return self._help_text()

        return None

    async def _generate_report(self, user_id: str, period: str) -> str:
        """
        Generate and send a report.

        The report is generated by the backend, then sent via WhatsApp.
        """
        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.post(
                    f"{self.openwa_url}/send-message",
                    json={
                        "user_id": user_id,
                        "phone": "",  # Backend resolves phone from user_id
                        "message": f"Inatengeneza ripoti ya {period}...",
                    },
                )

            # TODO: Call report generation service
            return f"Ripoti ya {period} imetumwa! Angalia WhatsApp yako. 📊"

        except Exception as e:
            logger.error(f"Report generation failed: {e}")
            return "Samahani, kuna tatizo la kutengeneza ripoti. Jaribu tena baadaye."

    async def _get_balance(self, user_id: str) -> str:
        """Get current balance summary."""
        # TODO: Query actual balance from database
        return (
            "📊 *Muhtasari wa Salio*\n\n"
            "Kuingiza: KES 0\n"
            "Kutumia: KES 0\n"
            "Salio: KES 0\n\n"
            "Tumia programu ya Msaidizi kwa maelezo zaidi."
        )

    async def _get_status(self, user_id: str) -> str:
        """Get connection and account status."""
        return (
            "✅ *Hali ya Akaunti*\n\n"
            "Akaunti: Hai\n"
            "WhatsApp: Imeunganishwa\n"
            "Ripoti: Zinatumwa kila siku saa 7 usiku\n\n"
            "Tumia programu ya Msaidizi kwa maelezo zaidi."
        )

    def _help_text(self) -> str:
        """Return help text in Swahili."""
        return (
            "🤖 *Msaidizi WhatsApp Bot*\n\n"
            "Amri zinazopatikana:\n\n"
            "📋 *Ripoti*\n"
            "• Ripoti ya leo — Ripoti ya siku\n"
            "• Ripoti ya wiki — Ripoti ya wiki\n"
            "• Ripoti ya mwezi — Ripoti ya mwezi\n\n"
            "💰 *Salio*\n"
            "• Salio — Angalia salio lako\n\n"
            "ℹ️ *Msaada*\n"
            "• Msaada — Onyesha amri hizi\n"
            "• Hali — Hali ya akaunti\n\n"
            "📅 Ripoti ya kila siku inatumwa saa 7 usiku.\n"
            "Tumia programu ya Msaidizi kwa kuingiza manunuzi."
        )

    def _unknown_command_response(self, text: str) -> str:
        """Response for unrecognized messages."""
        return (
            "Sielewi ujumbe wako. 🤔\n\n"
            "Tuma 'Msaada' kuona amri zinazopatikana.\n\n"
            "💡 Kidokezo: Tumia programu ya Msaidizi "
            "kwa kuingiza manunuzi na kuzungumza."
        )


# ── Singleton ────────────────────────────────────────────────────

_bot: Optional[WhatsAppBot] = None


def get_whatsapp_bot() -> WhatsAppBot:
    """Get or create the singleton WhatsAppBot."""
    global _bot
    if _bot is None:
        _bot = WhatsAppBot()
    return _bot
